# Generated by Django 5.2.14 on 2026-05-26 13:54

import django.db.models.deletion
import posts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리 목록',
            },
        ),
        migrations.CreateModel(
            name='groupsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('min_members', models.PositiveIntegerField(verbose_name='최소 모집인원')),
                ('current_members', models.PositiveIntegerField(default=0, verbose_name='현재 참여인원')),
                ('price_per', models.PositiveIntegerField(verbose_name='1/n 금액')),
                ('location', models.CharField(max_length=100, verbose_name='거래 장소')),
                ('deadline', models.DateTimeField(verbose_name='모집 마감일')),
                ('link', models.URLField(blank=True, verbose_name='실제 판매 링크')),
                ('status', models.CharField(choices=[('recruiting', '모집중'), ('closed', '마감'), ('done', '완료')], default='recruiting', max_length=20, verbose_name='상태')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='posts.category', verbose_name='카테고리')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_groups', to=settings.AUTH_USER_MODEL, verbose_name='호스트')),
            ],
            options={
                'verbose_name': '공구',
                'verbose_name_plural': '공구 목록',
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='groupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=posts.models.upload_to_groups, verbose_name='공구 이미지')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='이미지 순서')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupImages', to='posts.groupspost')),
            ],
            options={
                'verbose_name': '공구 이미지',
                'verbose_name_plural': '공구 이미지 목록',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='sharingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('quantity', models.PositiveIntegerField(verbose_name='물건 개수')),
                ('location', models.CharField(max_length=200, verbose_name='거래 장소')),
                ('trade_time', models.DateTimeField(verbose_name='거래 시간')),
                ('deadline', models.DateTimeField(verbose_name='모집 마감 시간')),
                ('status', models.CharField(choices=[('recruiting', '모집중'), ('closed', '마감'), ('done', '완료')], default='open', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharings', to='posts.category', verbose_name='카테고리')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sharings', to=settings.AUTH_USER_MODEL, verbose_name='호스트')),
            ],
            options={
                'verbose_name': '나눔',
                'verbose_name_plural': '나눔 목록',
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='SharingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=posts.models.upload_to_sharing)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='이미지 순서')),
                ('sharing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.sharingpost')),
            ],
            options={
                'verbose_name': '나눔 이미지',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='groupsParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='참여 상태')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupsParticipants', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupsParticipants', to='posts.groupspost')),
            ],
            options={
                'verbose_name': '공구 참여',
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SharingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '거절')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharingParticipants', to=settings.AUTH_USER_MODEL)),
                ('sharing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='posts.sharingpost')),
            ],
            options={
                'verbose_name': '나눔 신청',
                'unique_together': {('sharing', 'user')},
            },
        ),
    ]
