# Generated by Django 5.2.14 on 2026-05-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupspost',
            options={'verbose_name': '공구', 'verbose_name_plural': '공구 목록'},
        ),
        migrations.AlterModelOptions(
            name='sharingpost',
            options={'verbose_name': '나눔', 'verbose_name_plural': '나눔 목록'},
        ),
    ]
