# Generated by Django 5.2.14 on 2026-05-27 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_groupspost_options_alter_sharingpost_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='posts.groupspost')),
                ('sharing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='posts.sharingpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '찜',
                'constraints': [models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('user', 'group'), name='unique_wish_group'), models.UniqueConstraint(condition=models.Q(('sharing__isnull', False)), fields=('user', 'sharing'), name='unique_wish_sharing')],
            },
        ),
    ]
