# Generated by Django 5.2.14 on 2026-05-30 02:28

import django.db.models.deletion
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_wish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharingimage',
            options={'ordering': ['order'], 'verbose_name': '나눔 이미지', 'verbose_name_plural': '나눔 이미지 목록'},
        ),
        migrations.RemoveField(
            model_name='sharingpost',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sharingpost',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='sharingimage',
            name='photo',
            field=models.ImageField(upload_to=posts.models.upload_to_sharing, verbose_name='나눔 이미지'),
        ),
        migrations.AlterField(
            model_name='sharingimage',
            name='sharing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareImage', to='posts.sharingpost'),
        ),
    ]
