# Generated by Django 5.2.14 on 2026-05-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_sharingimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharingpost',
            name='location',
        ),
        migrations.AlterField(
            model_name='sharingpost',
            name='status',
            field=models.CharField(choices=[('recruiting', '모집중'), ('closed', '마감'), ('done', '완료')], default='recruiting', max_length=20),
        ),
    ]
