# Generated by Django 5.2.14 on 2026-05-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_sharingpost_location_alter_sharingpost_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharingpost',
            name='trade_time',
        ),
        migrations.AddField(
            model_name='sharingpost',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='거래 장소'),
        ),
    ]
