# Generated by Django 5.2.14 on 2026-05-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_sharingpost_trade_time_sharingpost_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingpost',
            name='location',
            field=models.CharField(default='미지정', max_length=100, verbose_name='거래 장소'),
            preserve_default=False,
        ),
    ]
