# Generated by Django 5.2.14 on 2026-05-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('posts', '0007_alter_sharingpost_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('group_post__isnull', False)), fields=('group_post',), name='unique_chat_room_group_post'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('sharing_post__isnull', False)), fields=('sharing_post',), name='unique_chat_room_sharing_post'),
        ),
    ]
