"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
# 보안 설정
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# 환경 변수로부터 ALLOWED_HOSTS를 받아와 공백을 제거하고 리스트로 변환
ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', '*').split(',') if host.strip()]
KAKAO_REST_API_KEY = os.getenv('KAKAO_REST_API_KEY')
SMS_API_KEY = os.getenv('SMS_API_KEY')
SMS_API_SECRET = os.getenv('SMS_API_SECRET')
SMS_SENDER = os.getenv('SMS_SENDER')
SMS_VERIFICATION_TTL_SECONDS = int(os.getenv('SMS_VERIFICATION_TTL_SECONDS', '300'))
SMS_RESEND_COOLDOWN_SECONDS = int(os.getenv('SMS_RESEND_COOLDOWN_SECONDS', '60'))

# 로그인 및 로그아웃 리다이렉트 설정
LOGIN_URL = 'accounts:login'  # 로그인 필요 시 로그인 페이지로 이동
LOGIN_REDIRECT_URL = '/posts/groups/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Application definition

INSTALLED_APPS = [
    'daphne',
    'accounts',
    'chat',
    'posts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 👈 배포 환경에서 static 파일 서빙을 위해 반드시 필요합니다!
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Channels 설정
ASGI_APPLICATION = 'config.asgi.application'

# Channels 레이어(메모리 백엔드, 개발용)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/' # URL에서 정적 파일 접근 경로
STATICFILES_DIRS = [BASE_DIR / "static"] # 루트의 공통 static/ 폴더 경로

# collectstatic 실행 시 모을 경로 (배포 시 필요)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise가 최적화(압축 및 캐싱)된 파일 보관을 지원하도록 설정
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = 'media/' # URL에서 미디어 파일 접근 경로
MEDIA_ROOT = BASE_DIR / 'media' # 실제 미디어 파일 저장 경로

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
